=== CarlosVV/jaxb-xew-plugin/src/test/resources/com/sun/tools/xjc/addon/xew/element-mixed.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	jaxb:version="2.0"
	targetNamespace="http://foo.org/"
	xmlns:foo="http://foo.org/"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
>
	<xs:annotation>
		<xs:appinfo>
			<jaxb:schemaBindings>
				<jaxb:package name="element_mixed" />
			</jaxb:schemaBindings>
		</xs:appinfo>
	</xs:annotation>

	<xs:complexType name="b" mixed="true">
		<xs:sequence minOccurs="0">
			<xs:element name="i" type="foo:i" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="i" mixed="true">
		<xs:sequence minOccurs="0">
			<xs:element name="b" type="foo:b" />
		</xs:sequence>
	</xs:complexType>

	<!--
		Example of element with no fields.
	-->
	<xs:complexType name="br" />

	<xs:simpleType name="text">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:simpleType name="number">
		<xs:restriction base="xs:int" />
	</xs:simpleType>

	<!--
		Example of "List<Object>" field + @XmlElements annotation.
	-->
	<xs:complexType name="formatted-text">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="i" type="foo:i" />
			<xs:element name="b" type="foo:b" />
			<xs:element name="br" type="foo:br" />
		</xs:choice>
	</xs:complexType>

	<!--
		Example of "List<Serializable>" field + @XmlElements annotation.
	-->
	<xs:complexType name="fixed-text">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="text" type="foo:text" />
			<xs:element name="ref" type="foo:number" />
		</xs:choice>
	</xs:complexType>

	<!--
		Example of "List<JAXBElement<String>>" field + @XmlElementRefs annotation.
		Results scoped declarations @XmlElementDecl(..., scope = PrefixedText.class).
	-->
	<xs:complexType name="prefixed-text">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="prefix" type="foo:text" />
			<xs:element name="text" type="foo:text" />
			<xs:element name="suffix" type="foo:text" />
		</xs:choice>
	</xs:complexType>

	<xs:element name="any-text">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="formatted-text" type="foo:formatted-text" />
				<xs:element name="fixed-text" type="foo:fixed-text" />
				<xs:element name="prefixed-text" type="foo:prefixed-text" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CarlosVV/jaxb-xew-plugin/src/test/resources/com/sun/tools/xjc/addon/xew/element-mixed.xml
<?xml version="1.0" encoding="UTF-8"?>

<any-text xmlns="http://foo.org/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://foo.org/ element-mixed.xsd">
	<formatted-text>
		<b>This text<i>is</i> about us.</b>
		<br/>
		<i>Do you find it funny?</i>
	</formatted-text>
	<fixed-text>
		<text>The story</text>
		<ref>84</ref>
	</fixed-text>
	<prefixed-text>
		<prefix>poly</prefix>
		<text>sele</text>
		<suffix>nide</suffix>
	</prefixed-text>
</any-text>
